# Generated by Django 2.2.4 on 2021-05-13 15:12

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='provincia', chained_model_field='provincia', null=True, on_delete=django.db.models.deletion.CASCADE, to='prueba.Departamento')),
                ('localidad', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='departamento', chained_model_field='departamento', null=True, on_delete=django.db.models.deletion.CASCADE, to='prueba.Localidad')),
                ('provincia', models.ForeignKey(blank=True, limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='prueba.Provincia')),
            ],
        ),
        migrations.AddField(
            model_name='departamento',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.Provincia'),
        ),
    ]
