# Generated by Django 2.2.4 on 2021-05-13 17:08

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0003_auto_20210513_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccion',
            name='localidad',
        ),
        migrations.AlterField(
            model_name='direccion',
            name='departamento',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='provincia', chained_model_field='provincia', null=True, on_delete=django.db.models.deletion.CASCADE, to='prueba.Departamento'),
        ),
    ]
