# Generated by Django 2.2.5 on 2020-10-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('idcliente', models.IntegerField(primary_key=True, serialize=False)),
                ('cuit', models.CharField(blank=True, max_length=13, null=True)),
                ('idactividad', models.IntegerField()),
                ('idcalifica', models.IntegerField()),
                ('idestadocliente', models.IntegerField()),
                ('nombre', models.CharField(blank=True, max_length=60, null=True)),
                ('fantasia', models.CharField(blank=True, max_length=60, null=True)),
                ('direc_d', models.CharField(blank=True, max_length=60, null=True)),
                ('telef_d', models.CharField(blank=True, max_length=20, null=True)),
                ('email_d', models.CharField(blank=True, max_length=90, null=True)),
                ('bloqueado', models.CharField(blank=True, max_length=1, null=True)),
                ('idprovincias', models.CharField(blank=True, max_length=15, null=True)),
                ('localidad', models.CharField(blank=True, max_length=60, null=True)),
                ('direccion', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
    ]
